### ISSUE TITLE
Maven Central publication

### ISSUE THREAD

**Issue by aSemy** [marykdb/maryk#1]
Hi, I'd like to use MaryK but manually checking out the project and deploying it locally is a hassle. I'd be happy to help out with some PRs to prepare Maven Central publishing. 

I've managed to publish libraries to Maven Central before, and while it's not easy I did manage to make it work! It would be possible to make publishing a manual task, or triggered automatically by a GitHub Workflow. To prepare for Maven Central publishing I'd like to first update the Gradle build config to make the build config more idiomatic by using convention plugins to share build logic.

For example of what I'd like to do, take a look at https://github.com/adamko-dev/kotlinx-serialization-typescript-generator

Here's an overview of the proposed PRs:

1. Update Gradle config to use convention plugins
2. Add 'publishing' convention plugin (example: https://github.com/Quillraven/Fleks/blob/2f1d773b7b74989e129ebfcd8c6f4bcb34bce725/buildSrc/src/main/kotlin/buildsrc/plugins/publishing.gradle.kts)
3. Add 'publish' GitHub Workflow (example: https://github.com/Quillraven/Fleks/blob/2f1d773b7b74989e129ebfcd8c6f4bcb34bce725/.github/workflows/publish.yml) which could either be triggered manually, or automatically.

**Comment by jurmous** [comment]
Sure go ahead! 😄

**Comment by aSemy** [comment]
Nice, thanks!

Something that you'd have to do is to register the group ID on Sonatype https://central.sonatype.org/publish/publish-guide/#introduction - or have you already registered coordinates?

**Comment by jurmous** [comment]
Yes I have registered `io.maryk` and have already published https://github.com/marykdb/rocksdb-multiplatform there. This project depends on that library.

**Comment by aSemy** [comment]
Great! That makes it much easier.

I've set up some Gradle properties so you can add the publishing secrets into `$GRADLE_USER_HOME/gradle.properties` on your local machine

```properties
maryk_ossrhUsername=...
maryk_ossrhPassword=...
maryk_signing_key=...
maryk_signing_password=...
```

If you want to set up automatic publishing could you also add the publishing secrets to GitHub? If you add them to the marykdb organisation then you could re-use them for https://github.com/marykdb/rocksdb-multiplatform too.

```
MARYK_OSSRHUSERNAME
MARYK_OSSRHPASSWORD
MARYK_SIGNING_KEY
MARYK_SIGNING_PASSWORD
```

**Comment by jurmous** [comment]
Thanks for the work. The library is now published.
